### ISSUE TITLE
Accept button

### ISSUE THREAD

**Issue by Jbleedge** [Kkthnx/KkthnxUI_WoD#20]
Hello.
Fresh install (no other addons, fresh wtf) using this files (.zip): https://github.com/Kkthnx/KkthnxUI_WoD

First login: when prompted with reload option the accept button doesn't work for me
After every reloadUI, the message pops up again.
I've made a little capture, hope it helps:

https://youtu.be/fWRF6Rgnadc

Really want to test it, but I'm not familiar with github so maybe I got the wrong files?
It'll be awesome if you could tell me what should I do and also how can I keep this updated :P please help a github newbie!
Thank you for sharing your work!

**Comment by Kkthnx** [comment]
Fixed with commit https://github.com/Kkthnx/KkthnxUI_WoD/commit/544b333611ebcc6918bd3ec19aae32790acfc755
